//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catl.WebServices.MiFindCustomAndSfcDataServiceService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class BasicBOBeanException
    {
        
        private data dataField;
        
        private string detailsField;
        
        private int errorField;
        
        private errorMessage errorMessageField;
        
        private string fullMsgField;
        
        private string messageField;
        
        private exception origExceptionField;
        
        private stackTraceElement[] suppressedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public data data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public errorMessage errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fullMsg
        {
            get
            {
                return this.fullMsgField;
            }
            set
            {
                this.fullMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public exception origException
        {
            get
            {
                return this.origExceptionField;
            }
            set
            {
                this.origExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stackTrace", typeof(stackTraceElement), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stackTraceElement[] suppressed
        {
            get
            {
                return this.suppressedField;
            }
            set
            {
                this.suppressedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class data
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class throwable
    {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class stackTraceElement
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class exception : throwable
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(applicationMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(errorMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class baseObject
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(errorMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class applicationMessage : baseObject
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class errorMessage : applicationMessage
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class customDataOutParametricData
    {
        
        private ObjectAliasEnum categoryField;
        
        private string dataFieldField;
        
        private string dataAttributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ObjectAliasEnum category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dataField
        {
            get
            {
                return this.dataFieldField;
            }
            set
            {
                this.dataFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dataAttribute
        {
            get
            {
                return this.dataAttributeField;
            }
            set
            {
                this.dataAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sap.com/me/common")]
    public enum ObjectAliasEnum
    {
        
        /// <remarks/>
        ACTIVITY,
        
        /// <remarks/>
        ACTIVITY_GROUP,
        
        /// <remarks/>
        ACTIVITY_LOG,
        
        /// <remarks/>
        ALARM,
        
        /// <remarks/>
        ALARM_LOG,
        
        /// <remarks/>
        APPLICATION_SETTING,
        
        /// <remarks/>
        ATTACHMENT,
        
        /// <remarks/>
        ATTENDANCE_LOG,
        
        /// <remarks/>
        BACKGROUND_PROCESS,
        
        /// <remarks/>
        BOM,
        
        /// <remarks/>
        BOM_COMPONENT,
        
        /// <remarks/>
        BUYOFF,
        
        /// <remarks/>
        BUYOFF_LOG,
        
        /// <remarks/>
        CERTIFICATION,
        
        /// <remarks/>
        CNC_PROGRAM,
        
        /// <remarks/>
        CONTAINER,
        
        /// <remarks/>
        CONTAINER_DATA,
        
        /// <remarks/>
        COST_CENTER,
        
        /// <remarks/>
        CUSTOMER,
        
        /// <remarks/>
        DATA_FIELD,
        
        /// <remarks/>
        DATA_TYPE,
        
        /// <remarks/>
        DC_GROUP,
        
        /// <remarks/>
        DOCUMENT,
        
        /// <remarks/>
        INVENTORY,
        
        /// <remarks/>
        INVENTORY_LOG,
        
        /// <remarks/>
        ITEM_GROUP,
        
        /// <remarks/>
        LABOR_CHARGE_CODE,
        
        /// <remarks/>
        MESSAGE,
        
        /// <remarks/>
        MESSAGE_LOG,
        
        /// <remarks/>
        MESSAGE_TYPE,
        
        /// <remarks/>
        NC_CODE,
        
        /// <remarks/>
        NEXT_NUMBER,
        
        /// <remarks/>
        OPERATION,
        
        /// <remarks/>
        PROCESS_LOT,
        
        /// <remarks/>
        PRODUCTION_LOG,
        
        /// <remarks/>
        REASON_CODE,
        
        /// <remarks/>
        SAMPLE_PLAN,
        
        /// <remarks/>
        WORK_INSTRUCTION,
        
        /// <remarks/>
        ITEM,
        
        /// <remarks/>
        RESOURCE,
        
        /// <remarks/>
        ROUTER,
        
        /// <remarks/>
        SHOP_ORDER,
        
        /// <remarks/>
        ROUTER_STEP,
        
        /// <remarks/>
        ROUTER_OPERATION,
        
        /// <remarks/>
        SFC,
        
        /// <remarks/>
        USR,
        
        /// <remarks/>
        USER_GROUP,
        
        /// <remarks/>
        WORK_CENTER,
        
        /// <remarks/>
        WORKSTATION,
        
        /// <remarks/>
        RESOURCE_TYPE,
        
        /// <remarks/>
        CUSTOMER_ORDER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class masterData
    {
        
        private string categoryField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class findCustomAndSfcDataResponse
    {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        private string sfcField;
        
        private string inventoryField;
        
        private masterData[] masterDataArrayField;
        
        private customDataOutParametricData[] customDataArrayField;
        
        private string xyField;
        
        private string cSCField;
        
        private string systemITEMField;
        
        private string systemSFCField;
        
        private string markingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sfc
        {
            get
            {
                return this.sfcField;
            }
            set
            {
                this.sfcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string inventory
        {
            get
            {
                return this.inventoryField;
            }
            set
            {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("masterDataArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public masterData[] masterDataArray
        {
            get
            {
                return this.masterDataArrayField;
            }
            set
            {
                this.masterDataArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customDataArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public customDataOutParametricData[] customDataArray
        {
            get
            {
                return this.customDataArrayField;
            }
            set
            {
                this.customDataArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string xY
        {
            get
            {
                return this.xyField;
            }
            set
            {
                this.xyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CSC
        {
            get
            {
                return this.cSCField;
            }
            set
            {
                this.cSCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string systemITEM
        {
            get
            {
                return this.systemITEMField;
            }
            set
            {
                this.systemITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string systemSFC
        {
            get
            {
                return this.systemSFCField;
            }
            set
            {
                this.systemSFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string marking
        {
            get
            {
                return this.markingField;
            }
            set
            {
                this.markingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class miFindCustomAndSfcDataResponse
    {
        
        private findCustomAndSfcDataResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public findCustomAndSfcDataResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class customDataInParametricData
    {
        
        private ObjectAliasEnum categoryField;
        
        private string dataFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ObjectAliasEnum category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dataField
        {
            get
            {
                return this.dataFieldField;
            }
            set
            {
                this.dataFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class findCustomAndSfcDataRequest
    {
        
        private string siteField;
        
        private string operationField;
        
        private string operationRevisionField;
        
        private string resourceField;
        
        private ObjectAliasEnum[] masterDataArrayField;
        
        private customDataInParametricData[] customDataArrayField;
        
        private string userField;
        
        private string activityField;
        
        private string sfcField;
        
        private string inventoryField;
        
        private bool findSfcByInventoryField;
        
        private modeProcessSFC modeProcessSFCField;
        
        private bool isGetXYField;
        
        private bool isGetCSCField;
        
        private string sfcOrderField;
        
        private string targetOrderField;
        
        private string checkInventoryABField;
        
        private bool showMarkingField;
        
        private bool showMarkingFieldSpecified;
        
        private string findInventoryByGbtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string operationRevision
        {
            get
            {
                return this.operationRevisionField;
            }
            set
            {
                this.operationRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("masterDataArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ObjectAliasEnum[] masterDataArray
        {
            get
            {
                return this.masterDataArrayField;
            }
            set
            {
                this.masterDataArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customDataArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public customDataInParametricData[] customDataArray
        {
            get
            {
                return this.customDataArrayField;
            }
            set
            {
                this.customDataArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string activity
        {
            get
            {
                return this.activityField;
            }
            set
            {
                this.activityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string sfc
        {
            get
            {
                return this.sfcField;
            }
            set
            {
                this.sfcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string inventory
        {
            get
            {
                return this.inventoryField;
            }
            set
            {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool findSfcByInventory
        {
            get
            {
                return this.findSfcByInventoryField;
            }
            set
            {
                this.findSfcByInventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public modeProcessSFC modeProcessSFC
        {
            get
            {
                return this.modeProcessSFCField;
            }
            set
            {
                this.modeProcessSFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public bool isGetXY
        {
            get
            {
                return this.isGetXYField;
            }
            set
            {
                this.isGetXYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool isGetCSC
        {
            get
            {
                return this.isGetCSCField;
            }
            set
            {
                this.isGetCSCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string sfcOrder
        {
            get
            {
                return this.sfcOrderField;
            }
            set
            {
                this.sfcOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string targetOrder
        {
            get
            {
                return this.targetOrderField;
            }
            set
            {
                this.targetOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string checkInventoryAB
        {
            get
            {
                return this.checkInventoryABField;
            }
            set
            {
                this.checkInventoryABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public bool showMarking
        {
            get
            {
                return this.showMarkingField;
            }
            set
            {
                this.showMarkingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showMarkingSpecified
        {
            get
            {
                return this.showMarkingFieldSpecified;
            }
            set
            {
                this.showMarkingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string findInventoryByGbt
        {
            get
            {
                return this.findInventoryByGbtField;
            }
            set
            {
                this.findInventoryByGbtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public enum modeProcessSFC
    {
        
        /// <remarks/>
        MODE_NONE,
        
        /// <remarks/>
        MODE_START_SFC,
        
        /// <remarks/>
        MODE_COMPLETE_SFC,
        
        /// <remarks/>
        MODE_PASS_SFC,
        
        /// <remarks/>
        MODE_START_COMPLETE_SFC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class miFindCustomAndSfcData
    {
        
        private findCustomAndSfcDataRequest findCustomAndSfcDataRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public findCustomAndSfcDataRequest FindCustomAndSfcDataRequest
        {
            get
            {
                return this.findCustomAndSfcDataRequestField;
            }
            set
            {
                this.findCustomAndSfcDataRequestField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://machineintegration.ws.atlmes.com/", ConfigurationName="Catl.WebServices.MiFindCustomAndSfcDataServiceService.MiFindCustomAndSfcDataServi" +
        "ce")]
    public interface MiFindCustomAndSfcDataService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Catl.WebServices.MiFindCustomAndSfcDataServiceService.BasicBOBeanException), Action="", Name="BasicBOBeanException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseObject))]
        System.Threading.Tasks.Task<Catl.WebServices.MiFindCustomAndSfcDataServiceService.miFindCustomAndSfcDataResponse1> miFindCustomAndSfcDataAsync(Catl.WebServices.MiFindCustomAndSfcDataServiceService.miFindCustomAndSfcDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class miFindCustomAndSfcDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiFindCustomAndSfcDataServiceService.miFindCustomAndSfcData miFindCustomAndSfcData;
        
        public miFindCustomAndSfcDataRequest()
        {
        }
        
        public miFindCustomAndSfcDataRequest(Catl.WebServices.MiFindCustomAndSfcDataServiceService.miFindCustomAndSfcData miFindCustomAndSfcData)
        {
            this.miFindCustomAndSfcData = miFindCustomAndSfcData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class miFindCustomAndSfcDataResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiFindCustomAndSfcDataServiceService.miFindCustomAndSfcDataResponse miFindCustomAndSfcDataResponse;
        
        public miFindCustomAndSfcDataResponse1()
        {
        }
        
        public miFindCustomAndSfcDataResponse1(Catl.WebServices.MiFindCustomAndSfcDataServiceService.miFindCustomAndSfcDataResponse miFindCustomAndSfcDataResponse)
        {
            this.miFindCustomAndSfcDataResponse = miFindCustomAndSfcDataResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface MiFindCustomAndSfcDataServiceChannel : Catl.WebServices.MiFindCustomAndSfcDataServiceService.MiFindCustomAndSfcDataService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MiFindCustomAndSfcDataServiceClient : System.ServiceModel.ClientBase<Catl.WebServices.MiFindCustomAndSfcDataServiceService.MiFindCustomAndSfcDataService>, Catl.WebServices.MiFindCustomAndSfcDataServiceService.MiFindCustomAndSfcDataService
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MiFindCustomAndSfcDataServiceClient() : 
                base(MiFindCustomAndSfcDataServiceClient.GetDefaultBinding(), MiFindCustomAndSfcDataServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MiFindCustomAndSfcDataServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiFindCustomAndSfcDataServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MiFindCustomAndSfcDataServiceClient.GetBindingForEndpoint(endpointConfiguration), MiFindCustomAndSfcDataServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiFindCustomAndSfcDataServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MiFindCustomAndSfcDataServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiFindCustomAndSfcDataServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MiFindCustomAndSfcDataServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiFindCustomAndSfcDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.MiFindCustomAndSfcDataServiceService.miFindCustomAndSfcDataResponse1> Catl.WebServices.MiFindCustomAndSfcDataServiceService.MiFindCustomAndSfcDataService.miFindCustomAndSfcDataAsync(Catl.WebServices.MiFindCustomAndSfcDataServiceService.miFindCustomAndSfcDataRequest request)
        {
            return base.Channel.miFindCustomAndSfcDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.MiFindCustomAndSfcDataServiceService.miFindCustomAndSfcDataResponse1> miFindCustomAndSfcDataAsync(Catl.WebServices.MiFindCustomAndSfcDataServiceService.miFindCustomAndSfcData miFindCustomAndSfcData)
        {
            Catl.WebServices.MiFindCustomAndSfcDataServiceService.miFindCustomAndSfcDataRequest inValue = new Catl.WebServices.MiFindCustomAndSfcDataServiceService.miFindCustomAndSfcDataRequest();
            inValue.miFindCustomAndSfcData = miFindCustomAndSfcData;
            return ((Catl.WebServices.MiFindCustomAndSfcDataServiceService.MiFindCustomAndSfcDataService)(this)).miFindCustomAndSfcDataAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiFindCustomAndSfcDataServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiFindCustomAndSfcDataServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://lymesbp203.catlbattery.com:50300/atlmeswebservice/MiFindCustomAndSfcDataSe" +
                        "rviceService");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MiFindCustomAndSfcDataServiceClient.GetBindingForEndpoint(EndpointConfiguration.MiFindCustomAndSfcDataServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MiFindCustomAndSfcDataServiceClient.GetEndpointAddress(EndpointConfiguration.MiFindCustomAndSfcDataServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            MiFindCustomAndSfcDataServicePort,
        }
    }
}
