//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catl.WebServices.MiCustomDCForCellServiceService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customcelldc.ws.atlmes.com/")]
    public partial class ParseException
    {
        
        private int errorOffsetField;
        
        private string messageField;
        
        private stackTraceElement[] suppressedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorOffset
        {
            get
            {
                return this.errorOffsetField;
            }
            set
            {
                this.errorOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stackTrace", typeof(stackTraceElement), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stackTraceElement[] suppressed
        {
            get
            {
                return this.suppressedField;
            }
            set
            {
                this.suppressedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customcelldc.ws.atlmes.com/")]
    public partial class stackTraceElement
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customcelldc.ws.atlmes.com/")]
    public partial class getZeroZoneTimeResponse
    {
        
        private long returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customcelldc.ws.atlmes.com/")]
    public partial class getZeroZoneTime
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customcelldc.ws.atlmes.com/")]
    public partial class miCustomDCForCellResponse
    {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customcelldc.ws.atlmes.com/")]
    public partial class cellCustomDCCheckResponse
    {
        
        private miCustomDCForCellResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public miCustomDCForCellResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customcelldc.ws.atlmes.com/")]
    public partial class miCustomDCForCellInventoryData
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customcelldc.ws.atlmes.com/")]
    public partial class miCustomDCForCellInventory
    {
        
        private string inventoryIdField;
        
        private string markingField;
        
        private miCustomDCForCellInventoryData[] inventoryDatalistField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string inventoryId
        {
            get
            {
                return this.inventoryIdField;
            }
            set
            {
                this.inventoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string marking
        {
            get
            {
                return this.markingField;
            }
            set
            {
                this.markingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inventoryDatalist", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public miCustomDCForCellInventoryData[] inventoryDatalist
        {
            get
            {
                return this.inventoryDatalistField;
            }
            set
            {
                this.inventoryDatalistField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customcelldc.ws.atlmes.com/")]
    public partial class miCustomDCForCellRequest
    {
        
        private string siteField;
        
        private string dcSequenceField;
        
        private string userField;
        
        private string multispecField;
        
        private string operationField;
        
        private string resourceField;
        
        private miCustomDCForCellInventory[] inventoryListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dcSequence
        {
            get
            {
                return this.dcSequenceField;
            }
            set
            {
                this.dcSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Multispec
        {
            get
            {
                return this.multispecField;
            }
            set
            {
                this.multispecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inventoryList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public miCustomDCForCellInventory[] inventoryList
        {
            get
            {
                return this.inventoryListField;
            }
            set
            {
                this.inventoryListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customcelldc.ws.atlmes.com/")]
    public partial class cellCustomDCCheck
    {
        
        private miCustomDCForCellRequest requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public miCustomDCForCellRequest Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://customcelldc.ws.atlmes.com/", ConfigurationName="Catl.WebServices.MiCustomDCForCellServiceService.MiCustomDCForCellService")]
    public interface MiCustomDCForCellService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Catl.WebServices.MiCustomDCForCellServiceService.cellCustomDCCheckResponse1> cellCustomDCCheckAsync(Catl.WebServices.MiCustomDCForCellServiceService.cellCustomDCCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Catl.WebServices.MiCustomDCForCellServiceService.ParseException), Action="", Name="ParseException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Catl.WebServices.MiCustomDCForCellServiceService.getZeroZoneTimeResponse1> getZeroZoneTimeAsync(Catl.WebServices.MiCustomDCForCellServiceService.getZeroZoneTimeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cellCustomDCCheckRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://customcelldc.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiCustomDCForCellServiceService.cellCustomDCCheck cellCustomDCCheck;
        
        public cellCustomDCCheckRequest()
        {
        }
        
        public cellCustomDCCheckRequest(Catl.WebServices.MiCustomDCForCellServiceService.cellCustomDCCheck cellCustomDCCheck)
        {
            this.cellCustomDCCheck = cellCustomDCCheck;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cellCustomDCCheckResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://customcelldc.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiCustomDCForCellServiceService.cellCustomDCCheckResponse cellCustomDCCheckResponse;
        
        public cellCustomDCCheckResponse1()
        {
        }
        
        public cellCustomDCCheckResponse1(Catl.WebServices.MiCustomDCForCellServiceService.cellCustomDCCheckResponse cellCustomDCCheckResponse)
        {
            this.cellCustomDCCheckResponse = cellCustomDCCheckResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getZeroZoneTimeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://customcelldc.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiCustomDCForCellServiceService.getZeroZoneTime getZeroZoneTime;
        
        public getZeroZoneTimeRequest()
        {
        }
        
        public getZeroZoneTimeRequest(Catl.WebServices.MiCustomDCForCellServiceService.getZeroZoneTime getZeroZoneTime)
        {
            this.getZeroZoneTime = getZeroZoneTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getZeroZoneTimeResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://customcelldc.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiCustomDCForCellServiceService.getZeroZoneTimeResponse getZeroZoneTimeResponse;
        
        public getZeroZoneTimeResponse1()
        {
        }
        
        public getZeroZoneTimeResponse1(Catl.WebServices.MiCustomDCForCellServiceService.getZeroZoneTimeResponse getZeroZoneTimeResponse)
        {
            this.getZeroZoneTimeResponse = getZeroZoneTimeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface MiCustomDCForCellServiceChannel : Catl.WebServices.MiCustomDCForCellServiceService.MiCustomDCForCellService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MiCustomDCForCellServiceClient : System.ServiceModel.ClientBase<Catl.WebServices.MiCustomDCForCellServiceService.MiCustomDCForCellService>, Catl.WebServices.MiCustomDCForCellServiceService.MiCustomDCForCellService
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MiCustomDCForCellServiceClient() : 
                base(MiCustomDCForCellServiceClient.GetDefaultBinding(), MiCustomDCForCellServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MiCustomDCForCellServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiCustomDCForCellServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MiCustomDCForCellServiceClient.GetBindingForEndpoint(endpointConfiguration), MiCustomDCForCellServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiCustomDCForCellServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MiCustomDCForCellServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiCustomDCForCellServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MiCustomDCForCellServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiCustomDCForCellServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.MiCustomDCForCellServiceService.cellCustomDCCheckResponse1> Catl.WebServices.MiCustomDCForCellServiceService.MiCustomDCForCellService.cellCustomDCCheckAsync(Catl.WebServices.MiCustomDCForCellServiceService.cellCustomDCCheckRequest request)
        {
            return base.Channel.cellCustomDCCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.MiCustomDCForCellServiceService.cellCustomDCCheckResponse1> cellCustomDCCheckAsync(Catl.WebServices.MiCustomDCForCellServiceService.cellCustomDCCheck cellCustomDCCheck)
        {
            Catl.WebServices.MiCustomDCForCellServiceService.cellCustomDCCheckRequest inValue = new Catl.WebServices.MiCustomDCForCellServiceService.cellCustomDCCheckRequest();
            inValue.cellCustomDCCheck = cellCustomDCCheck;
            return ((Catl.WebServices.MiCustomDCForCellServiceService.MiCustomDCForCellService)(this)).cellCustomDCCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.MiCustomDCForCellServiceService.getZeroZoneTimeResponse1> Catl.WebServices.MiCustomDCForCellServiceService.MiCustomDCForCellService.getZeroZoneTimeAsync(Catl.WebServices.MiCustomDCForCellServiceService.getZeroZoneTimeRequest request)
        {
            return base.Channel.getZeroZoneTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.MiCustomDCForCellServiceService.getZeroZoneTimeResponse1> getZeroZoneTimeAsync(Catl.WebServices.MiCustomDCForCellServiceService.getZeroZoneTime getZeroZoneTime)
        {
            Catl.WebServices.MiCustomDCForCellServiceService.getZeroZoneTimeRequest inValue = new Catl.WebServices.MiCustomDCForCellServiceService.getZeroZoneTimeRequest();
            inValue.getZeroZoneTime = getZeroZoneTime;
            return ((Catl.WebServices.MiCustomDCForCellServiceService.MiCustomDCForCellService)(this)).getZeroZoneTimeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiCustomDCForCellServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiCustomDCForCellServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://lymesp024.catlbattery.com:50400/atlmeswebservice/MiCustomDCForCellServiceS" +
                        "ervice");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MiCustomDCForCellServiceClient.GetBindingForEndpoint(EndpointConfiguration.MiCustomDCForCellServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MiCustomDCForCellServiceClient.GetEndpointAddress(EndpointConfiguration.MiCustomDCForCellServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            MiCustomDCForCellServicePort,
        }
    }
}
