//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catl.WebServices.DataCollectForResourceFAI
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class BusinessException
    {
        
        private object[] detailsField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private stackTraceElement[] suppressedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object[] details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stackTrace", typeof(stackTraceElement), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stackTraceElement[] suppressed
        {
            get
            {
                return this.suppressedField;
            }
            set
            {
                this.suppressedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class data
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class BasicBOBeanException
    {
        
        private data dataField;
        
        private string detailsField;
        
        private int errorField;
        
        private errorMessage errorMessageField;
        
        private string fullMsgField;
        
        private string messageField;
        
        private exception origExceptionField;
        
        private stackTraceElement[] suppressedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public data data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public errorMessage errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fullMsg
        {
            get
            {
                return this.fullMsgField;
            }
            set
            {
                this.fullMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public exception origException
        {
            get
            {
                return this.origExceptionField;
            }
            set
            {
                this.origExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stackTrace", typeof(stackTraceElement), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stackTraceElement[] suppressed
        {
            get
            {
                return this.suppressedField;
            }
            set
            {
                this.suppressedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class errorMessage : applicationMessage
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(errorMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class applicationMessage : baseObject
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(applicationMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(errorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractDataSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseDataSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(systemBase))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class baseObject
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseDataSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(systemBase))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public abstract partial class abstractDataSource : baseObject
    {
        
        private string dataSourceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dataSourceName
        {
            get
            {
                return this.dataSourceNameField;
            }
            set
            {
                this.dataSourceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(systemBase))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class baseDataSource : abstractDataSource
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class systemBase : baseDataSource
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class exception : throwable
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class throwable
    {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class stackTraceElement
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class getDcParametersResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class getDcParameters
    {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private string arg2Field;
        
        private string arg3Field;
        
        private string arg4Field;
        
        private string arg5Field;
        
        private string arg6Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arg2
        {
            get
            {
                return this.arg2Field;
            }
            set
            {
                this.arg2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string arg3
        {
            get
            {
                return this.arg3Field;
            }
            set
            {
                this.arg3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string arg4
        {
            get
            {
                return this.arg4Field;
            }
            set
            {
                this.arg4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string arg5
        {
            get
            {
                return this.arg5Field;
            }
            set
            {
                this.arg5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string arg6
        {
            get
            {
                return this.arg6Field;
            }
            set
            {
                this.arg6Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class getCustomDataValueExResponse
    {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class getCustomDataValueEx
    {
        
        private string arg0Field;
        
        private ObjectAliasEnum arg1Field;
        
        private bool arg1FieldSpecified;
        
        private string arg2Field;
        
        private string arg3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ObjectAliasEnum arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg1Specified
        {
            get
            {
                return this.arg1FieldSpecified;
            }
            set
            {
                this.arg1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arg2
        {
            get
            {
                return this.arg2Field;
            }
            set
            {
                this.arg2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string arg3
        {
            get
            {
                return this.arg3Field;
            }
            set
            {
                this.arg3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sap.com/me/common")]
    public enum ObjectAliasEnum
    {
        
        /// <remarks/>
        ACTIVITY,
        
        /// <remarks/>
        ACTIVITY_GROUP,
        
        /// <remarks/>
        ACTIVITY_LOG,
        
        /// <remarks/>
        ALARM,
        
        /// <remarks/>
        ALARM_LOG,
        
        /// <remarks/>
        APPLICATION_SETTING,
        
        /// <remarks/>
        ATTACHMENT,
        
        /// <remarks/>
        ATTENDANCE_LOG,
        
        /// <remarks/>
        BACKGROUND_PROCESS,
        
        /// <remarks/>
        BOM,
        
        /// <remarks/>
        BOM_COMPONENT,
        
        /// <remarks/>
        BUYOFF,
        
        /// <remarks/>
        BUYOFF_LOG,
        
        /// <remarks/>
        CERTIFICATION,
        
        /// <remarks/>
        CNC_PROGRAM,
        
        /// <remarks/>
        CONTAINER,
        
        /// <remarks/>
        CONTAINER_DATA,
        
        /// <remarks/>
        COST_CENTER,
        
        /// <remarks/>
        CUSTOMER,
        
        /// <remarks/>
        DATA_FIELD,
        
        /// <remarks/>
        DATA_TYPE,
        
        /// <remarks/>
        DC_GROUP,
        
        /// <remarks/>
        DOCUMENT,
        
        /// <remarks/>
        INVENTORY,
        
        /// <remarks/>
        INVENTORY_LOG,
        
        /// <remarks/>
        ITEM_GROUP,
        
        /// <remarks/>
        LABOR_CHARGE_CODE,
        
        /// <remarks/>
        MESSAGE,
        
        /// <remarks/>
        MESSAGE_LOG,
        
        /// <remarks/>
        MESSAGE_TYPE,
        
        /// <remarks/>
        NC_CODE,
        
        /// <remarks/>
        NEXT_NUMBER,
        
        /// <remarks/>
        OPERATION,
        
        /// <remarks/>
        PROCESS_LOT,
        
        /// <remarks/>
        PRODUCTION_LOG,
        
        /// <remarks/>
        REASON_CODE,
        
        /// <remarks/>
        SAMPLE_PLAN,
        
        /// <remarks/>
        WORK_INSTRUCTION,
        
        /// <remarks/>
        ITEM,
        
        /// <remarks/>
        RESOURCE,
        
        /// <remarks/>
        ROUTER,
        
        /// <remarks/>
        SHOP_ORDER,
        
        /// <remarks/>
        ROUTER_STEP,
        
        /// <remarks/>
        ROUTER_OPERATION,
        
        /// <remarks/>
        SFC,
        
        /// <remarks/>
        USR,
        
        /// <remarks/>
        USER_GROUP,
        
        /// <remarks/>
        WORK_CENTER,
        
        /// <remarks/>
        WORKSTATION,
        
        /// <remarks/>
        RESOURCE_TYPE,
        
        /// <remarks/>
        CUSTOMER_ORDER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class erroAvoidResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class erroAvoid
    {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private string arg2Field;
        
        private string arg3Field;
        
        private string arg4Field;
        
        private string arg5Field;
        
        private systemBase arg6Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arg2
        {
            get
            {
                return this.arg2Field;
            }
            set
            {
                this.arg2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string arg3
        {
            get
            {
                return this.arg3Field;
            }
            set
            {
                this.arg3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string arg4
        {
            get
            {
                return this.arg4Field;
            }
            set
            {
                this.arg4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string arg5
        {
            get
            {
                return this.arg5Field;
            }
            set
            {
                this.arg5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public systemBase arg6
        {
            get
            {
                return this.arg6Field;
            }
            set
            {
                this.arg6Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class machineIntegrationResourceDcResponse
    {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorCodeSpecified
        {
            get
            {
                return this.errorCodeFieldSpecified;
            }
            set
            {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class dataCollectForResourceFAIResponse
    {
        
        private machineIntegrationResourceDcResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public machineIntegrationResourceDcResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class machineIntegrationParametricData
    {
        
        private string nameField;
        
        private string valueField;
        
        private ParameterDataType dataTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ParameterDataType dataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sap.com/me/datacollection")]
    public enum ParameterDataType
    {
        
        /// <remarks/>
        NUMBER,
        
        /// <remarks/>
        TEXT,
        
        /// <remarks/>
        FORMULA,
        
        /// <remarks/>
        BOOLEAN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class dataCollectForResourceFAIRequest
    {
        
        private string siteField;
        
        private string dcGroupField;
        
        private string dcModeField;
        
        private string sfcField;
        
        private string materialField;
        
        private string materialRevisionField;
        
        private string dcGroupRevisionField;
        
        private string resourceField;
        
        private string operationField;
        
        private string operationRevisionField;
        
        private string dcGroupSequenceField;
        
        private string userField;
        
        private machineIntegrationParametricData[] parametricDataArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dcGroup
        {
            get
            {
                return this.dcGroupField;
            }
            set
            {
                this.dcGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dcMode
        {
            get
            {
                return this.dcModeField;
            }
            set
            {
                this.dcModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sfc
        {
            get
            {
                return this.sfcField;
            }
            set
            {
                this.sfcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string material
        {
            get
            {
                return this.materialField;
            }
            set
            {
                this.materialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string materialRevision
        {
            get
            {
                return this.materialRevisionField;
            }
            set
            {
                this.materialRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string dcGroupRevision
        {
            get
            {
                return this.dcGroupRevisionField;
            }
            set
            {
                this.dcGroupRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string operationRevision
        {
            get
            {
                return this.operationRevisionField;
            }
            set
            {
                this.operationRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string dcGroupSequence
        {
            get
            {
                return this.dcGroupSequenceField;
            }
            set
            {
                this.dcGroupSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parametricDataArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public machineIntegrationParametricData[] parametricDataArray
        {
            get
            {
                return this.parametricDataArrayField;
            }
            set
            {
                this.parametricDataArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machine.ws.atlmes.com/")]
    public partial class dataCollectForResourceFAI
    {
        
        private dataCollectForResourceFAIRequest resourceRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dataCollectForResourceFAIRequest resourceRequest
        {
            get
            {
                return this.resourceRequestField;
            }
            set
            {
                this.resourceRequestField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://machine.ws.atlmes.com/", ConfigurationName="DataCollectForResourceFAIServiceService.DataCollectForResourceFAIService")]
    public interface DataCollectForResourceFAIService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicBOBeanException))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDcParametersResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDcParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCustomDataValueExResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCustomDataValueEx))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseObject))]
        System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceFAI.dataCollectForResourceFAIResponse1> dataCollectForResourceFAIAsync(Catl.WebServices.DataCollectForResourceFAI.dataCollectForResourceFAIRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Catl.WebServices.DataCollectForResourceFAI.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicBOBeanException))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDcParametersResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDcParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCustomDataValueExResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCustomDataValueEx))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseObject))]
        System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceFAI.erroAvoidResponse1> erroAvoidAsync(Catl.WebServices.DataCollectForResourceFAI.erroAvoidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Catl.WebServices.DataCollectForResourceFAI.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicBOBeanException))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDcParametersResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDcParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCustomDataValueExResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCustomDataValueEx))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseObject))]
        System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceFAI.getCustomDataValueExResponse1> getCustomDataValueExAsync(Catl.WebServices.DataCollectForResourceFAI.getCustomDataValueExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Catl.WebServices.DataCollectForResourceFAI.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Catl.WebServices.DataCollectForResourceFAI.BasicBOBeanException), Action="", Name="BasicBOBeanException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicBOBeanException))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDcParametersResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDcParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCustomDataValueExResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCustomDataValueEx))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseObject))]
        System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceFAI.getDcParametersResponse1> getDcParametersAsync(Catl.WebServices.DataCollectForResourceFAI.getDcParametersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dataCollectForResourceFAIRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machine.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.DataCollectForResourceFAI.dataCollectForResourceFAI dataCollectForResourceFAI;
        
        public dataCollectForResourceFAIRequest1()
        {
        }
        
        public dataCollectForResourceFAIRequest1(Catl.WebServices.DataCollectForResourceFAI.dataCollectForResourceFAI dataCollectForResourceFAI)
        {
            this.dataCollectForResourceFAI = dataCollectForResourceFAI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dataCollectForResourceFAIResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machine.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.DataCollectForResourceFAI.dataCollectForResourceFAIResponse dataCollectForResourceFAIResponse;
        
        public dataCollectForResourceFAIResponse1()
        {
        }
        
        public dataCollectForResourceFAIResponse1(Catl.WebServices.DataCollectForResourceFAI.dataCollectForResourceFAIResponse dataCollectForResourceFAIResponse)
        {
            this.dataCollectForResourceFAIResponse = dataCollectForResourceFAIResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class erroAvoidRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machine.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.DataCollectForResourceFAI.erroAvoid erroAvoid;
        
        public erroAvoidRequest()
        {
        }
        
        public erroAvoidRequest(Catl.WebServices.DataCollectForResourceFAI.erroAvoid erroAvoid)
        {
            this.erroAvoid = erroAvoid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class erroAvoidResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machine.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.DataCollectForResourceFAI.erroAvoidResponse erroAvoidResponse;
        
        public erroAvoidResponse1()
        {
        }
        
        public erroAvoidResponse1(Catl.WebServices.DataCollectForResourceFAI.erroAvoidResponse erroAvoidResponse)
        {
            this.erroAvoidResponse = erroAvoidResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCustomDataValueExRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machine.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.DataCollectForResourceFAI.getCustomDataValueEx getCustomDataValueEx;
        
        public getCustomDataValueExRequest()
        {
        }
        
        public getCustomDataValueExRequest(Catl.WebServices.DataCollectForResourceFAI.getCustomDataValueEx getCustomDataValueEx)
        {
            this.getCustomDataValueEx = getCustomDataValueEx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCustomDataValueExResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machine.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.DataCollectForResourceFAI.getCustomDataValueExResponse getCustomDataValueExResponse;
        
        public getCustomDataValueExResponse1()
        {
        }
        
        public getCustomDataValueExResponse1(Catl.WebServices.DataCollectForResourceFAI.getCustomDataValueExResponse getCustomDataValueExResponse)
        {
            this.getCustomDataValueExResponse = getCustomDataValueExResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDcParametersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machine.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.DataCollectForResourceFAI.getDcParameters getDcParameters;
        
        public getDcParametersRequest()
        {
        }
        
        public getDcParametersRequest(Catl.WebServices.DataCollectForResourceFAI.getDcParameters getDcParameters)
        {
            this.getDcParameters = getDcParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDcParametersResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machine.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.DataCollectForResourceFAI.getDcParametersResponse getDcParametersResponse;
        
        public getDcParametersResponse1()
        {
        }
        
        public getDcParametersResponse1(Catl.WebServices.DataCollectForResourceFAI.getDcParametersResponse getDcParametersResponse)
        {
            this.getDcParametersResponse = getDcParametersResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface DataCollectForResourceFAIServiceChannel : Catl.WebServices.DataCollectForResourceFAI.DataCollectForResourceFAIService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class DataCollectForResourceFAIServiceClient : System.ServiceModel.ClientBase<Catl.WebServices.DataCollectForResourceFAI.DataCollectForResourceFAIService>, Catl.WebServices.DataCollectForResourceFAI.DataCollectForResourceFAIService
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataCollectForResourceFAIServiceClient() : 
                base(DataCollectForResourceFAIServiceClient.GetDefaultBinding(), DataCollectForResourceFAIServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DataCollectForResourceFAIServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCollectForResourceFAIServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(DataCollectForResourceFAIServiceClient.GetBindingForEndpoint(endpointConfiguration), DataCollectForResourceFAIServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCollectForResourceFAIServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataCollectForResourceFAIServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCollectForResourceFAIServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataCollectForResourceFAIServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCollectForResourceFAIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceFAI.dataCollectForResourceFAIResponse1> Catl.WebServices.DataCollectForResourceFAI.DataCollectForResourceFAIService.dataCollectForResourceFAIAsync(Catl.WebServices.DataCollectForResourceFAI.dataCollectForResourceFAIRequest1 request)
        {
            return base.Channel.dataCollectForResourceFAIAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceFAI.dataCollectForResourceFAIResponse1> dataCollectForResourceFAIAsync(Catl.WebServices.DataCollectForResourceFAI.dataCollectForResourceFAI dataCollectForResourceFAI)
        {
            Catl.WebServices.DataCollectForResourceFAI.dataCollectForResourceFAIRequest1 inValue = new Catl.WebServices.DataCollectForResourceFAI.dataCollectForResourceFAIRequest1();
            inValue.dataCollectForResourceFAI = dataCollectForResourceFAI;
            return ((Catl.WebServices.DataCollectForResourceFAI.DataCollectForResourceFAIService)(this)).dataCollectForResourceFAIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceFAI.erroAvoidResponse1> Catl.WebServices.DataCollectForResourceFAI.DataCollectForResourceFAIService.erroAvoidAsync(Catl.WebServices.DataCollectForResourceFAI.erroAvoidRequest request)
        {
            return base.Channel.erroAvoidAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceFAI.erroAvoidResponse1> erroAvoidAsync(Catl.WebServices.DataCollectForResourceFAI.erroAvoid erroAvoid)
        {
            Catl.WebServices.DataCollectForResourceFAI.erroAvoidRequest inValue = new Catl.WebServices.DataCollectForResourceFAI.erroAvoidRequest();
            inValue.erroAvoid = erroAvoid;
            return ((Catl.WebServices.DataCollectForResourceFAI.DataCollectForResourceFAIService)(this)).erroAvoidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceFAI.getCustomDataValueExResponse1> Catl.WebServices.DataCollectForResourceFAI.DataCollectForResourceFAIService.getCustomDataValueExAsync(Catl.WebServices.DataCollectForResourceFAI.getCustomDataValueExRequest request)
        {
            return base.Channel.getCustomDataValueExAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceFAI.getCustomDataValueExResponse1> getCustomDataValueExAsync(Catl.WebServices.DataCollectForResourceFAI.getCustomDataValueEx getCustomDataValueEx)
        {
            Catl.WebServices.DataCollectForResourceFAI.getCustomDataValueExRequest inValue = new Catl.WebServices.DataCollectForResourceFAI.getCustomDataValueExRequest();
            inValue.getCustomDataValueEx = getCustomDataValueEx;
            return ((Catl.WebServices.DataCollectForResourceFAI.DataCollectForResourceFAIService)(this)).getCustomDataValueExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceFAI.getDcParametersResponse1> Catl.WebServices.DataCollectForResourceFAI.DataCollectForResourceFAIService.getDcParametersAsync(Catl.WebServices.DataCollectForResourceFAI.getDcParametersRequest request)
        {
            return base.Channel.getDcParametersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceFAI.getDcParametersResponse1> getDcParametersAsync(Catl.WebServices.DataCollectForResourceFAI.getDcParameters getDcParameters)
        {
            Catl.WebServices.DataCollectForResourceFAI.getDcParametersRequest inValue = new Catl.WebServices.DataCollectForResourceFAI.getDcParametersRequest();
            inValue.getDcParameters = getDcParameters;
            return ((Catl.WebServices.DataCollectForResourceFAI.DataCollectForResourceFAIService)(this)).getDcParametersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataCollectForResourceFAIServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataCollectForResourceFAIServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://lymesp024.catlbattery.com:52400/atlmeswebservice/DataCollectForResourceFAI" +
                        "ServiceService");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DataCollectForResourceFAIServiceClient.GetBindingForEndpoint(EndpointConfiguration.DataCollectForResourceFAIServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DataCollectForResourceFAIServiceClient.GetEndpointAddress(EndpointConfiguration.DataCollectForResourceFAIServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            DataCollectForResourceFAIServicePort,
        }
    }
}
