//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisDummy.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisDummy.Lang.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MES测试 的本地化字符串。
        /// </summary>
        public static string MES测试 {
            get {
                return ResourceManager.GetString("MES测试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MES配置 的本地化字符串。
        /// </summary>
        public static string MES配置 {
            get {
                return ResourceManager.GetString("MES配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D视觉拍照状态码异常 的本地化字符串。
        /// </summary>
        public static string Msg_3D视觉拍照状态码异常 {
            get {
                return ResourceManager.GetString("Msg_3D视觉拍照状态码异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MST信号为空，将从PLC重新读取... 的本地化字符串。
        /// </summary>
        public static string Msg_MST信号为空将从PLC重新读取 {
            get {
                return ResourceManager.GetString("Msg_MST信号为空将从PLC重新读取", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MST信号已从PLC恢复 的本地化字符串。
        /// </summary>
        public static string Msg_MST信号已从PLC恢复 {
            get {
                return ResourceManager.GetString("Msg_MST信号已从PLC恢复", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC参数错误 的本地化字符串。
        /// </summary>
        public static string Msg_PLC参数错误 {
            get {
                return ResourceManager.GetString("Msg_PLC参数错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次输入的密码必须一致 的本地化字符串。
        /// </summary>
        public static string Msg_两次输入的密码必须一致 {
            get {
                return ResourceManager.GetString("Msg_两次输入的密码必须一致", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string Msg_保存成功 {
            get {
                return ResourceManager.GetString("Msg_保存成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改前 的本地化字符串。
        /// </summary>
        public static string Msg_修改前 {
            get {
                return ResourceManager.GetString("Msg_修改前", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局参数变动 的本地化字符串。
        /// </summary>
        public static string Msg_全局参数变动 {
            get {
                return ResourceManager.GetString("Msg_全局参数变动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换到用户失败，请检查服务器是否启动或操作员凭据 的本地化字符串。
        /// </summary>
        public static string Msg_切换到用户失败请检查服务器是否启动或操作员凭据 {
            get {
                return ResourceManager.GetString("Msg_切换到用户失败请检查服务器是否启动或操作员凭据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化 的本地化字符串。
        /// </summary>
        public static string Msg_初始化 {
            get {
                return ResourceManager.GetString("Msg_初始化", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除账户完成 的本地化字符串。
        /// </summary>
        public static string Msg_删除账户完成 {
            get {
                return ResourceManager.GetString("Msg_删除账户完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除账户成功 的本地化字符串。
        /// </summary>
        public static string Msg_删除账户成功 {
            get {
                return ResourceManager.GetString("Msg_删除账户成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除账户错误 的本地化字符串。
        /// </summary>
        public static string Msg_删除账户错误 {
            get {
                return ResourceManager.GetString("Msg_删除账户错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载流程失败 的本地化字符串。
        /// </summary>
        public static string Msg_加载流程失败 {
            get {
                return ResourceManager.GetString("Msg_加载流程失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称不可为空 的本地化字符串。
        /// </summary>
        public static string Msg_名称不可为空 {
            get {
                return ResourceManager.GetString("Msg_名称不可为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向PLC写数据错误 的本地化字符串。
        /// </summary>
        public static string Msg_向PLC写数据错误 {
            get {
                return ResourceManager.GetString("Msg_向PLC写数据错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码与工卡不可均为空 的本地化字符串。
        /// </summary>
        public static string Msg_密码与工卡不可均为空 {
            get {
                return ResourceManager.GetString("Msg_密码与工卡不可均为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已修改密码 的本地化字符串。
        /// </summary>
        public static string Msg_已修改密码 {
            get {
                return ResourceManager.GetString("Msg_已修改密码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已修改权限分配 的本地化字符串。
        /// </summary>
        public static string Msg_已修改权限分配 {
            get {
                return ResourceManager.GetString("Msg_已修改权限分配", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已创建用户 的本地化字符串。
        /// </summary>
        public static string Msg_已创建用户 {
            get {
                return ResourceManager.GetString("Msg_已创建用户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已删除用户 的本地化字符串。
        /// </summary>
        public static string Msg_已删除用户 {
            get {
                return ResourceManager.GetString("Msg_已删除用户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已登录 的本地化字符串。
        /// </summary>
        public static string Msg_已登录 {
            get {
                return ResourceManager.GetString("Msg_已登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前INI文件不含有首件的配置段 的本地化字符串。
        /// </summary>
        public static string Msg_当前INI文件不含有首件的配置段 {
            get {
                return ResourceManager.GetString("Msg_当前INI文件不含有首件的配置段", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前密码不可为空！ 的本地化字符串。
        /// </summary>
        public static string Msg_当前密码不可为空 {
            get {
                return ResourceManager.GetString("Msg_当前密码不可为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照失败 的本地化字符串。
        /// </summary>
        public static string Msg_拍照失败 {
            get {
                return ResourceManager.GetString("Msg_拍照失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照成功 的本地化字符串。
        /// </summary>
        public static string Msg_拍照成功 {
            get {
                return ResourceManager.GetString("Msg_拍照成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到PLC拍照请求 的本地化字符串。
        /// </summary>
        public static string Msg_收到PLC拍照请求 {
            get {
                return ResourceManager.GetString("Msg_收到PLC拍照请求", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不可为空！ 的本地化字符串。
        /// </summary>
        public static string Msg_新密码不可为空 {
            get {
                return ResourceManager.GetString("Msg_新密码不可为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不得为空 的本地化字符串。
        /// </summary>
        public static string Msg_新密码不得为空 {
            get {
                return ResourceManager.GetString("Msg_新密码不得为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法加载3D视觉控制器 的本地化字符串。
        /// </summary>
        public static string Msg_无法加载3D视觉控制器 {
            get {
                return ResourceManager.GetString("Msg_无法加载3D视觉控制器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标定球拍照请求 的本地化字符串。
        /// </summary>
        public static string Msg_标定球拍照请求 {
            get {
                return ResourceManager.GetString("Msg_标定球拍照请求", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常工作拍照 的本地化字符串。
        /// </summary>
        public static string Msg_正常工作拍照 {
            get {
                return ResourceManager.GetString("Msg_正常工作拍照", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程未注册 或未注册成 的本地化字符串。
        /// </summary>
        public static string Msg_流程未注册或未注册成 {
            get {
                return ResourceManager.GetString("Msg_流程未注册或未注册成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精度校验 的本地化字符串。
        /// </summary>
        public static string Msg_精度校验 {
            get {
                return ResourceManager.GetString("Msg_精度校验", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统错误 的本地化字符串。
        /// </summary>
        public static string Msg_系统错误 {
            get {
                return ResourceManager.GetString("Msg_系统错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取全局变量功能类失败 的本地化字符串。
        /// </summary>
        public static string Msg_获取全局变量功能类失败 {
            get {
                return ResourceManager.GetString("Msg_获取全局变量功能类失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视觉输入参数 的本地化字符串。
        /// </summary>
        public static string Msg_视觉输入参数 {
            get {
                return ResourceManager.GetString("Msg_视觉输入参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置全局变量失败 的本地化字符串。
        /// </summary>
        public static string Msg_设置全局变量失败 {
            get {
                return ResourceManager.GetString("Msg_设置全局变量失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        public static string Msg_请输入密码 {
            get {
                return ResourceManager.GetString("Msg_请输入密码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号名不可为空！ 的本地化字符串。
        /// </summary>
        public static string Msg_账号名不可为空 {
            get {
                return ResourceManager.GetString("Msg_账号名不可为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首件参数变动 的本地化字符串。
        /// </summary>
        public static string Msg_首件参数变动 {
            get {
                return ResourceManager.GetString("Msg_首件参数变动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N点标定 的本地化字符串。
        /// </summary>
        public static string N点标定 {
            get {
                return ResourceManager.GetString("N点标定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC日志 的本地化字符串。
        /// </summary>
        public static string PLC日志 {
            get {
                return ResourceManager.GetString("PLC日志", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VM全局变量 的本地化字符串。
        /// </summary>
        public static string VM全局变量 {
            get {
                return ResourceManager.GetString("VM全局变量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string 上一页 {
            get {
                return ResourceManager.GetString("上一页", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string 下一页 {
            get {
                return ResourceManager.GetString("下一页", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 九点标定 的本地化字符串。
        /// </summary>
        public static string 九点标定 {
            get {
                return ResourceManager.GetString("九点标定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string 保存 {
            get {
                return ResourceManager.GetString("保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string 修改密码 {
            get {
                return ResourceManager.GetString("修改密码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public static string 值 {
            get {
                return ResourceManager.GetString("值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 像素精度 的本地化字符串。
        /// </summary>
        public static string 像素精度 {
            get {
                return ResourceManager.GetString("像素精度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局变量 的本地化字符串。
        /// </summary>
        public static string 全局变量 {
            get {
                return ResourceManager.GetString("全局变量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换用户 的本地化字符串。
        /// </summary>
        public static string 切换用户 {
            get {
                return ResourceManager.GetString("切换用户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建用户 的本地化字符串。
        /// </summary>
        public static string 创建用户 {
            get {
                return ResourceManager.GetString("创建用户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string 删除 {
            get {
                return ResourceManager.GetString("删除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷卡登录 的本地化字符串。
        /// </summary>
        public static string 刷卡登录 {
            get {
                return ResourceManager.GetString("刷卡登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string 刷新 {
            get {
                return ResourceManager.GetString("刷新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能号 的本地化字符串。
        /// </summary>
        public static string 功能号 {
            get {
                return ResourceManager.GetString("功能号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数设置 的本地化字符串。
        /// </summary>
        public static string 参数设置 {
            get {
                return ResourceManager.GetString("参数设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string 名称 {
            get {
                return ResourceManager.GetString("名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应NG 的本地化字符串。
        /// </summary>
        public static string 响应NG {
            get {
                return ResourceManager.GetString("响应NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应OK 的本地化字符串。
        /// </summary>
        public static string 响应OK {
            get {
                return ResourceManager.GetString("响应OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string 姓名 {
            get {
                return ResourceManager.GetString("姓名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string 密码 {
            get {
                return ResourceManager.GetString("密码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码(二次确认) 的本地化字符串。
        /// </summary>
        public static string 密码_二次确认_ {
            get {
                return ResourceManager.GetString("密码(二次确认)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码登录 的本地化字符串。
        /// </summary>
        public static string 密码登录 {
            get {
                return ResourceManager.GetString("密码登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工卡 的本地化字符串。
        /// </summary>
        public static string 工卡 {
            get {
                return ResourceManager.GetString("工卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程状态 的本地化字符串。
        /// </summary>
        public static string 工程状态 {
            get {
                return ResourceManager.GetString("工程状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已登录时间: 的本地化字符串。
        /// </summary>
        public static string 已登录时间 {
            get {
                return ResourceManager.GetString("已登录时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前密码 的本地化字符串。
        /// </summary>
        public static string 当前密码 {
            get {
                return ResourceManager.GetString("当前密码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前账号 的本地化字符串。
        /// </summary>
        public static string 当前账号 {
            get {
                return ResourceManager.GetString("当前账号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前页码 的本地化字符串。
        /// </summary>
        public static string 当前页码 {
            get {
                return ResourceManager.GetString("当前页码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心跳响应 的本地化字符串。
        /// </summary>
        public static string 心跳响应 {
            get {
                return ResourceManager.GetString("心跳响应", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心跳请求 的本地化字符串。
        /// </summary>
        public static string 心跳请求 {
            get {
                return ResourceManager.GetString("心跳请求", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总页数 的本地化字符串。
        /// </summary>
        public static string 总页数 {
            get {
                return ResourceManager.GetString("总页数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次 的本地化字符串。
        /// </summary>
        public static string 批次 {
            get {
                return ResourceManager.GetString("批次", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警代码 的本地化字符串。
        /// </summary>
        public static string 报警代码 {
            get {
                return ResourceManager.GetString("报警代码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警日志 的本地化字符串。
        /// </summary>
        public static string 报警日志 {
            get {
                return ResourceManager.GetString("报警日志", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照位置 的本地化字符串。
        /// </summary>
        public static string 拍照位置 {
            get {
                return ResourceManager.GetString("拍照位置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照次数 的本地化字符串。
        /// </summary>
        public static string 拍照次数 {
            get {
                return ResourceManager.GetString("拍照次数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接口参数 的本地化字符串。
        /// </summary>
        public static string 接口参数 {
            get {
                return ResourceManager.GetString("接口参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string 操作 {
            get {
                return ResourceManager.GetString("操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作者: 的本地化字符串。
        /// </summary>
        public static string 操作者 {
            get {
                return ResourceManager.GetString("操作者", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string 新密码 {
            get {
                return ResourceManager.GetString("新密码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码(二次输入) 的本地化字符串。
        /// </summary>
        public static string 新密码_二次输入_ {
            get {
                return ResourceManager.GetString("新密码(二次输入)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋转中心 的本地化字符串。
        /// </summary>
        public static string 旋转中心 {
            get {
                return ResourceManager.GetString("旋转中心", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询日志 的本地化字符串。
        /// </summary>
        public static string 日志查询 {
            get {
                return ResourceManager.GetString("日志查询", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志消息 的本地化字符串。
        /// </summary>
        public static string 日志消息 {
            get {
                return ResourceManager.GetString("日志消息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string 更新 {
            get {
                return ResourceManager.GetString("更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        public static string 权限 {
            get {
                return ResourceManager.GetString("权限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来料方向 的本地化字符串。
        /// </summary>
        public static string 来料方向 {
            get {
                return ResourceManager.GetString("来料方向", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 极性结果 的本地化字符串。
        /// </summary>
        public static string 极性结果 {
            get {
                return ResourceManager.GetString("极性结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标定球拍照响应 的本地化字符串。
        /// </summary>
        public static string 标定球拍照响应 {
            get {
                return ResourceManager.GetString("标定球拍照响应", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标定球拍照完成请求 的本地化字符串。
        /// </summary>
        public static string 标定球拍照完成请求 {
            get {
                return ResourceManager.GetString("标定球拍照完成请求", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标定球拍照请求 的本地化字符串。
        /// </summary>
        public static string 标定球拍照请求 {
            get {
                return ResourceManager.GetString("标定球拍照请求", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组类型 的本地化字符串。
        /// </summary>
        public static string 模组类型 {
            get {
                return ResourceManager.GetString("模组类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在退出，请勿强行关闭: 的本地化字符串。
        /// </summary>
        public static string 正在退出请勿强行关闭 {
            get {
                return ResourceManager.GetString("正在退出请勿强行关闭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步长 的本地化字符串。
        /// </summary>
        public static string 步长 {
            get {
                return ResourceManager.GetString("步长", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泡棉层高 的本地化字符串。
        /// </summary>
        public static string 泡棉层高 {
            get {
                return ResourceManager.GetString("泡棉层高", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泡棉状态 的本地化字符串。
        /// </summary>
        public static string 泡棉状态 {
            get {
                return ResourceManager.GetString("泡棉状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销(切换成操作员) 的本地化字符串。
        /// </summary>
        public static string 注销_切换成操作员_ {
            get {
                return ResourceManager.GetString("注销(切换成操作员)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程 的本地化字符串。
        /// </summary>
        public static string 流程 {
            get {
                return ResourceManager.GetString("流程", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清屏 的本地化字符串。
        /// </summary>
        public static string 清屏 {
            get {
                return ResourceManager.GetString("清屏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位监控-垫片检测 的本地化字符串。
        /// </summary>
        public static string 点位监控_垫片检测 {
            get {
                return ResourceManager.GetString("点位监控-垫片检测", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位监控-大包装 的本地化字符串。
        /// </summary>
        public static string 点位监控_大包装 {
            get {
                return ResourceManager.GetString("点位监控-大包装", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位监控-模组入箱 的本地化字符串。
        /// </summary>
        public static string 点位监控_模组入箱 {
            get {
                return ResourceManager.GetString("点位监控-模组入箱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位监控-模组检测 的本地化字符串。
        /// </summary>
        public static string 点位监控_模组检测 {
            get {
                return ResourceManager.GetString("点位监控-模组检测", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位监控-模组贴标 的本地化字符串。
        /// </summary>
        public static string 点位监控_模组贴标 {
            get {
                return ResourceManager.GetString("点位监控-模组贴标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点检 的本地化字符串。
        /// </summary>
        public static string 点检 {
            get {
                return ResourceManager.GetString("点检", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特征大小 的本地化字符串。
        /// </summary>
        public static string 特征大小 {
            get {
                return ResourceManager.GetString("特征大小", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string 状态 {
            get {
                return ResourceManager.GetString("状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产管理 的本地化字符串。
        /// </summary>
        public static string 生产管理 {
            get {
                return ResourceManager.GetString("生产管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户操作 的本地化字符串。
        /// </summary>
        public static string 用户操作 {
            get {
                return ResourceManager.GetString("用户操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string 用户管理 {
            get {
                return ResourceManager.GetString("用户管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电芯列数 的本地化字符串。
        /// </summary>
        public static string 电芯列数 {
            get {
                return ResourceManager.GetString("电芯列数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电芯码 的本地化字符串。
        /// </summary>
        public static string 电芯码 {
            get {
                return ResourceManager.GetString("电芯码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string 登录 {
            get {
                return ResourceManager.GetString("登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机号 的本地化字符串。
        /// </summary>
        public static string 相机号 {
            get {
                return ResourceManager.GetString("相机号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止编辑 的本地化字符串。
        /// </summary>
        public static string 禁止编辑 {
            get {
                return ResourceManager.GetString("禁止编辑", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 的本地化字符串。
        /// </summary>
        public static string 筛选 {
            get {
                return ResourceManager.GetString("筛选", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理权限 的本地化字符串。
        /// </summary>
        public static string 管理权限 {
            get {
                return ResourceManager.GetString("管理权限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string 类型 {
            get {
                return ResourceManager.GetString("类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精度校验拍照响应 的本地化字符串。
        /// </summary>
        public static string 精度校验拍照响应 {
            get {
                return ResourceManager.GetString("精度校验拍照响应", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精度校验拍照请求 的本地化字符串。
        /// </summary>
        public static string 精度校验拍照请求 {
            get {
                return ResourceManager.GetString("精度校验拍照请求", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统用户 的本地化字符串。
        /// </summary>
        public static string 系统用户 {
            get {
                return ResourceManager.GetString("系统用户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维护模式 的本地化字符串。
        /// </summary>
        public static string 维护模式 {
            get {
                return ResourceManager.GetString("维护模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视觉工作拍照响应 的本地化字符串。
        /// </summary>
        public static string 视觉工作拍照响应 {
            get {
                return ResourceManager.GetString("视觉工作拍照响应", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视觉工作拍照请求 的本地化字符串。
        /// </summary>
        public static string 视觉工作拍照请求 {
            get {
                return ResourceManager.GetString("视觉工作拍照请求", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视觉方案 的本地化字符串。
        /// </summary>
        public static string 视觉方案 {
            get {
                return ResourceManager.GetString("视觉方案", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视觉监控 的本地化字符串。
        /// </summary>
        public static string 视觉监控 {
            get {
                return ResourceManager.GetString("视觉监控", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string 角色 {
            get {
                return ResourceManager.GetString("角色", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发拍照 的本地化字符串。
        /// </summary>
        public static string 触发拍照 {
            get {
                return ResourceManager.GetString("触发拍照", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备ID: 的本地化字符串。
        /// </summary>
        public static string 设备ID {
            get {
                return ResourceManager.GetString("设备ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        public static string 说明 {
            get {
                return ResourceManager.GetString("说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请刷卡登录 的本地化字符串。
        /// </summary>
        public static string 请刷卡登录 {
            get {
                return ResourceManager.GetString("请刷卡登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请稍等... 的本地化字符串。
        /// </summary>
        public static string 请稍等 {
            get {
                return ResourceManager.GetString("请稍等", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试工具 的本地化字符串。
        /// </summary>
        public static string 调试工具 {
            get {
                return ResourceManager.GetString("调试工具", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        public static string 账号 {
            get {
                return ResourceManager.GetString("账号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号名 的本地化字符串。
        /// </summary>
        public static string 账号名 {
            get {
                return ResourceManager.GetString("账号名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行日志 的本地化字符串。
        /// </summary>
        public static string 运行日志 {
            get {
                return ResourceManager.GetString("运行日志", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接参数 的本地化字符串。
        /// </summary>
        public static string 连接参数 {
            get {
                return ResourceManager.GetString("连接参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择流程 的本地化字符串。
        /// </summary>
        public static string 选择流程 {
            get {
                return ResourceManager.GetString("选择流程", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通用状态 的本地化字符串。
        /// </summary>
        public static string 通用状态 {
            get {
                return ResourceManager.GetString("通用状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置表单 的本地化字符串。
        /// </summary>
        public static string 重置表单 {
            get {
                return ResourceManager.GetString("重置表单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风冷片有无 的本地化字符串。
        /// </summary>
        public static string 风冷片有无 {
            get {
                return ResourceManager.GetString("风冷片有无", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首件调用 的本地化字符串。
        /// </summary>
        public static string 首件调用 {
            get {
                return ResourceManager.GetString("首件调用", resourceCulture);
            }
        }
    }
}
