//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catl.WebServices.MiCheckInventoryAttributesServiceService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class BusinessException
    {
        
        private object[] detailsField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private stackTraceElement[] suppressedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object[] details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stackTrace", typeof(stackTraceElement), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stackTraceElement[] suppressed
        {
            get
            {
                return this.suppressedField;
            }
            set
            {
                this.suppressedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class getSetPointParametersResponse
    {
        
        private getSetPointParametersResponseEntry[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public getSetPointParametersResponseEntry[] Return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class getSetPointParametersResponseEntry
    {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class getSetPointParameters
    {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private string arg2Field;
        
        private string arg3Field;
        
        private string[] arg4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arg2
        {
            get
            {
                return this.arg2Field;
            }
            set
            {
                this.arg2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string arg3
        {
            get
            {
                return this.arg3Field;
            }
            set
            {
                this.arg3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("arg4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string[] arg4
        {
            get
            {
                return this.arg4Field;
            }
            set
            {
                this.arg4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class getInventoryIDDataFieldResponse
    {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class getInventoryIDDataField
    {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private string arg2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arg2
        {
            get
            {
                return this.arg2Field;
            }
            set
            {
                this.arg2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class stackTraceElement
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class getNcListByInventoryID
    {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private string arg2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arg2
        {
            get
            {
                return this.arg2Field;
            }
            set
            {
                this.arg2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class checkInventoryDataFields
    {
        
        private string inventoryField;
        
        private string attributeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string inventory
        {
            get
            {
                return this.inventoryField;
            }
            set
            {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class checkInventoryAttributesResponse
    {
        
        private int codeField;
        
        private string messageField;
        
        private string failedSfcField;
        
        private string failedInventoryField;
        
        private checkInventoryDataFields[] inventoryDataFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string failedSfc
        {
            get
            {
                return this.failedSfcField;
            }
            set
            {
                this.failedSfcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string failedInventory
        {
            get
            {
                return this.failedInventoryField;
            }
            set
            {
                this.failedInventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inventoryDataFields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public checkInventoryDataFields[] inventoryDataFields
        {
            get
            {
                return this.inventoryDataFieldsField;
            }
            set
            {
                this.inventoryDataFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class miCheckInventoryAttributesResponse
    {
        
        private checkInventoryAttributesResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public checkInventoryAttributesResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class ModuleCellMarkingOrTimeCheckRequest
    {
        
        private string siteField;
        
        private string sfcField;
        
        private string operationField;
        
        private string operationRevisionField;
        
        private string resourceField;
        
        private string userField;
        
        private string activityIdField;
        
        private modeCheckInventory modeCheckInventoryField;
        
        private int requiredQuantityField;
        
        private string[] inventoryArrayField;
        
        private string[] inventoryAttributeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sfc
        {
            get
            {
                return this.sfcField;
            }
            set
            {
                this.sfcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string operationRevision
        {
            get
            {
                return this.operationRevisionField;
            }
            set
            {
                this.operationRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string activityId
        {
            get
            {
                return this.activityIdField;
            }
            set
            {
                this.activityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public modeCheckInventory modeCheckInventory
        {
            get
            {
                return this.modeCheckInventoryField;
            }
            set
            {
                this.modeCheckInventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int requiredQuantity
        {
            get
            {
                return this.requiredQuantityField;
            }
            set
            {
                this.requiredQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inventoryArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string[] inventoryArray
        {
            get
            {
                return this.inventoryArrayField;
            }
            set
            {
                this.inventoryArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttributeList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string[] inventoryAttributeList
        {
            get
            {
                return this.inventoryAttributeListField;
            }
            set
            {
                this.inventoryAttributeListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public enum modeCheckInventory
    {
        
        /// <remarks/>
        MODE_MARK_ONLY,
        
        /// <remarks/>
        MODE_TIME_ONLY,
        
        /// <remarks/>
        MODE_MARK_AND_TIME,
        
        /// <remarks/>
        MODE_NONE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class miCheckInventoryAttributes
    {
        
        private ModuleCellMarkingOrTimeCheckRequest checkInventoryAttributesRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ModuleCellMarkingOrTimeCheckRequest CheckInventoryAttributesRequest
        {
            get
            {
                return this.checkInventoryAttributesRequestField;
            }
            set
            {
                this.checkInventoryAttributesRequestField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://machineintegration.ws.atlmes.com/", ConfigurationName="Catl.WebServices.MiCheckInventoryAttributesServiceService.MiCheckInventoryAttribu" +
        "tesService")]
    public interface MiCheckInventoryAttributesService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSetPointParametersResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSetPointParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getInventoryIDDataFieldResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getInventoryIDDataField))]
        System.Threading.Tasks.Task<Catl.WebServices.MiCheckInventoryAttributesServiceService.miCheckInventoryAttributesResponse1> miCheckInventoryAttributesAsync(Catl.WebServices.MiCheckInventoryAttributesServiceService.miCheckInventoryAttributesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Catl.WebServices.MiCheckInventoryAttributesServiceService.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSetPointParametersResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSetPointParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getInventoryIDDataFieldResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getInventoryIDDataField))]
        System.Threading.Tasks.Task<Catl.WebServices.MiCheckInventoryAttributesServiceService.getNcListByInventoryIDResponse> getNcListByInventoryIDAsync(Catl.WebServices.MiCheckInventoryAttributesServiceService.getNcListByInventoryIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Catl.WebServices.MiCheckInventoryAttributesServiceService.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSetPointParametersResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSetPointParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getInventoryIDDataFieldResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getInventoryIDDataField))]
        System.Threading.Tasks.Task<Catl.WebServices.MiCheckInventoryAttributesServiceService.getInventoryIDDataFieldResponse1> getInventoryIDDataFieldAsync(Catl.WebServices.MiCheckInventoryAttributesServiceService.getInventoryIDDataFieldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Catl.WebServices.MiCheckInventoryAttributesServiceService.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSetPointParametersResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSetPointParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getInventoryIDDataFieldResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getInventoryIDDataField))]
        System.Threading.Tasks.Task<Catl.WebServices.MiCheckInventoryAttributesServiceService.getSetPointParametersResponse1> getSetPointParametersAsync(Catl.WebServices.MiCheckInventoryAttributesServiceService.getSetPointParametersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class miCheckInventoryAttributesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiCheckInventoryAttributesServiceService.miCheckInventoryAttributes miCheckInventoryAttributes;
        
        public miCheckInventoryAttributesRequest()
        {
        }
        
        public miCheckInventoryAttributesRequest(Catl.WebServices.MiCheckInventoryAttributesServiceService.miCheckInventoryAttributes miCheckInventoryAttributes)
        {
            this.miCheckInventoryAttributes = miCheckInventoryAttributes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class miCheckInventoryAttributesResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiCheckInventoryAttributesServiceService.miCheckInventoryAttributesResponse miCheckInventoryAttributesResponse;
        
        public miCheckInventoryAttributesResponse1()
        {
        }
        
        public miCheckInventoryAttributesResponse1(Catl.WebServices.MiCheckInventoryAttributesServiceService.miCheckInventoryAttributesResponse miCheckInventoryAttributesResponse)
        {
            this.miCheckInventoryAttributesResponse = miCheckInventoryAttributesResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNcListByInventoryIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiCheckInventoryAttributesServiceService.getNcListByInventoryID getNcListByInventoryID;
        
        public getNcListByInventoryIDRequest()
        {
        }
        
        public getNcListByInventoryIDRequest(Catl.WebServices.MiCheckInventoryAttributesServiceService.getNcListByInventoryID getNcListByInventoryID)
        {
            this.getNcListByInventoryID = getNcListByInventoryID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNcListByInventoryIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNcListByInventoryIDResponse", Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] getNcListByInventoryIDResponse1;
        
        public getNcListByInventoryIDResponse()
        {
        }
        
        public getNcListByInventoryIDResponse(string[] getNcListByInventoryIDResponse1)
        {
            this.getNcListByInventoryIDResponse1 = getNcListByInventoryIDResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInventoryIDDataFieldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiCheckInventoryAttributesServiceService.getInventoryIDDataField getInventoryIDDataField;
        
        public getInventoryIDDataFieldRequest()
        {
        }
        
        public getInventoryIDDataFieldRequest(Catl.WebServices.MiCheckInventoryAttributesServiceService.getInventoryIDDataField getInventoryIDDataField)
        {
            this.getInventoryIDDataField = getInventoryIDDataField;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInventoryIDDataFieldResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiCheckInventoryAttributesServiceService.getInventoryIDDataFieldResponse getInventoryIDDataFieldResponse;
        
        public getInventoryIDDataFieldResponse1()
        {
        }
        
        public getInventoryIDDataFieldResponse1(Catl.WebServices.MiCheckInventoryAttributesServiceService.getInventoryIDDataFieldResponse getInventoryIDDataFieldResponse)
        {
            this.getInventoryIDDataFieldResponse = getInventoryIDDataFieldResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSetPointParametersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiCheckInventoryAttributesServiceService.getSetPointParameters getSetPointParameters;
        
        public getSetPointParametersRequest()
        {
        }
        
        public getSetPointParametersRequest(Catl.WebServices.MiCheckInventoryAttributesServiceService.getSetPointParameters getSetPointParameters)
        {
            this.getSetPointParameters = getSetPointParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSetPointParametersResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiCheckInventoryAttributesServiceService.getSetPointParametersResponse getSetPointParametersResponse;
        
        public getSetPointParametersResponse1()
        {
        }
        
        public getSetPointParametersResponse1(Catl.WebServices.MiCheckInventoryAttributesServiceService.getSetPointParametersResponse getSetPointParametersResponse)
        {
            this.getSetPointParametersResponse = getSetPointParametersResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface MiCheckInventoryAttributesServiceChannel : Catl.WebServices.MiCheckInventoryAttributesServiceService.MiCheckInventoryAttributesService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MiCheckInventoryAttributesServiceClient : System.ServiceModel.ClientBase<Catl.WebServices.MiCheckInventoryAttributesServiceService.MiCheckInventoryAttributesService>, Catl.WebServices.MiCheckInventoryAttributesServiceService.MiCheckInventoryAttributesService
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MiCheckInventoryAttributesServiceClient() : 
                base(MiCheckInventoryAttributesServiceClient.GetDefaultBinding(), MiCheckInventoryAttributesServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MiCheckInventoryAttributesServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiCheckInventoryAttributesServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MiCheckInventoryAttributesServiceClient.GetBindingForEndpoint(endpointConfiguration), MiCheckInventoryAttributesServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiCheckInventoryAttributesServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MiCheckInventoryAttributesServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiCheckInventoryAttributesServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MiCheckInventoryAttributesServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiCheckInventoryAttributesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.MiCheckInventoryAttributesServiceService.miCheckInventoryAttributesResponse1> Catl.WebServices.MiCheckInventoryAttributesServiceService.MiCheckInventoryAttributesService.miCheckInventoryAttributesAsync(Catl.WebServices.MiCheckInventoryAttributesServiceService.miCheckInventoryAttributesRequest request)
        {
            return base.Channel.miCheckInventoryAttributesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.MiCheckInventoryAttributesServiceService.miCheckInventoryAttributesResponse1> miCheckInventoryAttributesAsync(Catl.WebServices.MiCheckInventoryAttributesServiceService.miCheckInventoryAttributes miCheckInventoryAttributes)
        {
            Catl.WebServices.MiCheckInventoryAttributesServiceService.miCheckInventoryAttributesRequest inValue = new Catl.WebServices.MiCheckInventoryAttributesServiceService.miCheckInventoryAttributesRequest();
            inValue.miCheckInventoryAttributes = miCheckInventoryAttributes;
            return ((Catl.WebServices.MiCheckInventoryAttributesServiceService.MiCheckInventoryAttributesService)(this)).miCheckInventoryAttributesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.MiCheckInventoryAttributesServiceService.getNcListByInventoryIDResponse> Catl.WebServices.MiCheckInventoryAttributesServiceService.MiCheckInventoryAttributesService.getNcListByInventoryIDAsync(Catl.WebServices.MiCheckInventoryAttributesServiceService.getNcListByInventoryIDRequest request)
        {
            return base.Channel.getNcListByInventoryIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.MiCheckInventoryAttributesServiceService.getNcListByInventoryIDResponse> getNcListByInventoryIDAsync(Catl.WebServices.MiCheckInventoryAttributesServiceService.getNcListByInventoryID getNcListByInventoryID)
        {
            Catl.WebServices.MiCheckInventoryAttributesServiceService.getNcListByInventoryIDRequest inValue = new Catl.WebServices.MiCheckInventoryAttributesServiceService.getNcListByInventoryIDRequest();
            inValue.getNcListByInventoryID = getNcListByInventoryID;
            return ((Catl.WebServices.MiCheckInventoryAttributesServiceService.MiCheckInventoryAttributesService)(this)).getNcListByInventoryIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.MiCheckInventoryAttributesServiceService.getInventoryIDDataFieldResponse1> Catl.WebServices.MiCheckInventoryAttributesServiceService.MiCheckInventoryAttributesService.getInventoryIDDataFieldAsync(Catl.WebServices.MiCheckInventoryAttributesServiceService.getInventoryIDDataFieldRequest request)
        {
            return base.Channel.getInventoryIDDataFieldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.MiCheckInventoryAttributesServiceService.getInventoryIDDataFieldResponse1> getInventoryIDDataFieldAsync(Catl.WebServices.MiCheckInventoryAttributesServiceService.getInventoryIDDataField getInventoryIDDataField)
        {
            Catl.WebServices.MiCheckInventoryAttributesServiceService.getInventoryIDDataFieldRequest inValue = new Catl.WebServices.MiCheckInventoryAttributesServiceService.getInventoryIDDataFieldRequest();
            inValue.getInventoryIDDataField = getInventoryIDDataField;
            return ((Catl.WebServices.MiCheckInventoryAttributesServiceService.MiCheckInventoryAttributesService)(this)).getInventoryIDDataFieldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.MiCheckInventoryAttributesServiceService.getSetPointParametersResponse1> Catl.WebServices.MiCheckInventoryAttributesServiceService.MiCheckInventoryAttributesService.getSetPointParametersAsync(Catl.WebServices.MiCheckInventoryAttributesServiceService.getSetPointParametersRequest request)
        {
            return base.Channel.getSetPointParametersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.MiCheckInventoryAttributesServiceService.getSetPointParametersResponse1> getSetPointParametersAsync(Catl.WebServices.MiCheckInventoryAttributesServiceService.getSetPointParameters getSetPointParameters)
        {
            Catl.WebServices.MiCheckInventoryAttributesServiceService.getSetPointParametersRequest inValue = new Catl.WebServices.MiCheckInventoryAttributesServiceService.getSetPointParametersRequest();
            inValue.getSetPointParameters = getSetPointParameters;
            return ((Catl.WebServices.MiCheckInventoryAttributesServiceService.MiCheckInventoryAttributesService)(this)).getSetPointParametersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiCheckInventoryAttributesServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiCheckInventoryAttributesServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://lymesbp205.catlbattery.com:50500/atlmeswebservice/MiCheckInventoryAttribut" +
                        "esServiceService");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MiCheckInventoryAttributesServiceClient.GetBindingForEndpoint(EndpointConfiguration.MiCheckInventoryAttributesServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MiCheckInventoryAttributesServiceClient.GetEndpointAddress(EndpointConfiguration.MiCheckInventoryAttributesServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            MiCheckInventoryAttributesServicePort,
        }
    }
}
