//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catl.WebServices.MiReleaseSfcWithActivityServiceService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class BasicBOBeanException
    {
        
        private data dataField;
        
        private string detailsField;
        
        private int errorField;
        
        private errorMessage errorMessageField;
        
        private string fullMsgField;
        
        private string messageField;
        
        private exception origExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public data data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public errorMessage errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fullMsg
        {
            get
            {
                return this.fullMsgField;
            }
            set
            {
                this.fullMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public exception origException
        {
            get
            {
                return this.origExceptionField;
            }
            set
            {
                this.origExceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class data
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class throwable
    {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class stackTraceElement
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class exception : throwable
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(applicationMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(errorMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class baseObject
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(errorMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class applicationMessage : baseObject
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class errorMessage : applicationMessage
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class sfcWithLocation
    {
        
        private string sfcField;
        
        private string carrierLocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sfc
        {
            get
            {
                return this.sfcField;
            }
            set
            {
                this.sfcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string carrierLocation
        {
            get
            {
                return this.carrierLocationField;
            }
            set
            {
                this.carrierLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class releaseSfcWithActivityResponse
    {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        private sfcWithLocation[] sfcArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sfcArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sfcWithLocation[] sfcArray
        {
            get
            {
                return this.sfcArrayField;
            }
            set
            {
                this.sfcArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class miReleaseSfcWithActivityByShoporderResponse
    {
        
        private releaseSfcWithActivityResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public releaseSfcWithActivityResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class releaseSfcWithActivityRequest
    {
        
        private string siteField;
        
        private string resourceField;
        
        private string operationField;
        
        private string operationRevisionField;
        
        private decimal sfcQtyField;
        
        private string activityField;
        
        private string userField;
        
        private string processlotField;
        
        private bool isCarrierTypeField;
        
        private columnOrRow columnOrRowFirstField;
        
        private bool columnOrRowFirstFieldSpecified;
        
        private string[] locationField;
        
        private modeProcessSFC modeProcessSFCField;
        
        private string shopOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string operationRevision
        {
            get
            {
                return this.operationRevisionField;
            }
            set
            {
                this.operationRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal sfcQty
        {
            get
            {
                return this.sfcQtyField;
            }
            set
            {
                this.sfcQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string activity
        {
            get
            {
                return this.activityField;
            }
            set
            {
                this.activityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string processlot
        {
            get
            {
                return this.processlotField;
            }
            set
            {
                this.processlotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool isCarrierType
        {
            get
            {
                return this.isCarrierTypeField;
            }
            set
            {
                this.isCarrierTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public columnOrRow ColumnOrRowFirst
        {
            get
            {
                return this.columnOrRowFirstField;
            }
            set
            {
                this.columnOrRowFirstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ColumnOrRowFirstSpecified
        {
            get
            {
                return this.columnOrRowFirstFieldSpecified;
            }
            set
            {
                this.columnOrRowFirstFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string[] location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public modeProcessSFC modeProcessSFC
        {
            get
            {
                return this.modeProcessSFCField;
            }
            set
            {
                this.modeProcessSFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string shopOrder
        {
            get
            {
                return this.shopOrderField;
            }
            set
            {
                this.shopOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public enum columnOrRow
    {
        
        /// <remarks/>
        ROW_FIRST,
        
        /// <remarks/>
        COLUMN_FIRST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public enum modeProcessSFC
    {
        
        /// <remarks/>
        MODE_NONE,
        
        /// <remarks/>
        MODE_START_SFC,
        
        /// <remarks/>
        MODE_COMPLETE_SFC,
        
        /// <remarks/>
        MODE_PASS_SFC,
        
        /// <remarks/>
        MODE_START_COMPLETE_SFC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class miReleaseSfcWithActivityByShoporder
    {
        
        private releaseSfcWithActivityRequest releaseSfcWithActivityRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public releaseSfcWithActivityRequest ReleaseSfcWithActivityRequest
        {
            get
            {
                return this.releaseSfcWithActivityRequestField;
            }
            set
            {
                this.releaseSfcWithActivityRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class BusinessException
    {
        
        private object[] detailsField;
        
        private int errorCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object[] details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://machineintegration.ws.atlmes.com/", ConfigurationName="Catl.WebServices.MiReleaseSfcWithActivityServiceService.MiReleaseSfcWithActivityS" +
        "ervice")]
    public interface MiReleaseSfcWithActivityService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Catl.WebServices.MiReleaseSfcWithActivityServiceService.BasicBOBeanException), Action="", Name="BasicBOBeanException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Catl.WebServices.MiReleaseSfcWithActivityServiceService.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseObject))]
        System.Threading.Tasks.Task<Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityByShoporderResponse1> miReleaseSfcWithActivityByShoporderAsync(Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityByShoporderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Catl.WebServices.MiReleaseSfcWithActivityServiceService.BasicBOBeanException), Action="", Name="BasicBOBeanException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseObject))]
        System.Threading.Tasks.Task<Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityResponse1> miReleaseSfcWithActivityAsync(Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class miReleaseSfcWithActivityByShoporderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityByShoporder miReleaseSfcWithActivityByShoporder;
        
        public miReleaseSfcWithActivityByShoporderRequest()
        {
        }
        
        public miReleaseSfcWithActivityByShoporderRequest(Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityByShoporder miReleaseSfcWithActivityByShoporder)
        {
            this.miReleaseSfcWithActivityByShoporder = miReleaseSfcWithActivityByShoporder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class miReleaseSfcWithActivityByShoporderResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityByShoporderResponse miReleaseSfcWithActivityByShoporderResponse;
        
        public miReleaseSfcWithActivityByShoporderResponse1()
        {
        }
        
        public miReleaseSfcWithActivityByShoporderResponse1(Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityByShoporderResponse miReleaseSfcWithActivityByShoporderResponse)
        {
            this.miReleaseSfcWithActivityByShoporderResponse = miReleaseSfcWithActivityByShoporderResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class miReleaseSfcWithActivity
    {
        
        private releaseSfcWithActivityRequest releaseSfcWithActivityRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public releaseSfcWithActivityRequest ReleaseSfcWithActivityRequest
        {
            get
            {
                return this.releaseSfcWithActivityRequestField;
            }
            set
            {
                this.releaseSfcWithActivityRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class miReleaseSfcWithActivityResponse
    {
        
        private releaseSfcWithActivityResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public releaseSfcWithActivityResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class miReleaseSfcWithActivityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivity miReleaseSfcWithActivity;
        
        public miReleaseSfcWithActivityRequest()
        {
        }
        
        public miReleaseSfcWithActivityRequest(Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivity miReleaseSfcWithActivity)
        {
            this.miReleaseSfcWithActivity = miReleaseSfcWithActivity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class miReleaseSfcWithActivityResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityResponse miReleaseSfcWithActivityResponse;
        
        public miReleaseSfcWithActivityResponse1()
        {
        }
        
        public miReleaseSfcWithActivityResponse1(Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityResponse miReleaseSfcWithActivityResponse)
        {
            this.miReleaseSfcWithActivityResponse = miReleaseSfcWithActivityResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface MiReleaseSfcWithActivityServiceChannel : Catl.WebServices.MiReleaseSfcWithActivityServiceService.MiReleaseSfcWithActivityService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MiReleaseSfcWithActivityServiceClient : System.ServiceModel.ClientBase<Catl.WebServices.MiReleaseSfcWithActivityServiceService.MiReleaseSfcWithActivityService>, Catl.WebServices.MiReleaseSfcWithActivityServiceService.MiReleaseSfcWithActivityService
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MiReleaseSfcWithActivityServiceClient() : 
                base(MiReleaseSfcWithActivityServiceClient.GetDefaultBinding(), MiReleaseSfcWithActivityServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MiReleaseSfcWithActivityServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiReleaseSfcWithActivityServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MiReleaseSfcWithActivityServiceClient.GetBindingForEndpoint(endpointConfiguration), MiReleaseSfcWithActivityServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiReleaseSfcWithActivityServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MiReleaseSfcWithActivityServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiReleaseSfcWithActivityServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MiReleaseSfcWithActivityServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiReleaseSfcWithActivityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityByShoporderResponse1> Catl.WebServices.MiReleaseSfcWithActivityServiceService.MiReleaseSfcWithActivityService.miReleaseSfcWithActivityByShoporderAsync(Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityByShoporderRequest request)
        {
            return base.Channel.miReleaseSfcWithActivityByShoporderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityByShoporderResponse1> miReleaseSfcWithActivityByShoporderAsync(Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityByShoporder miReleaseSfcWithActivityByShoporder)
        {
            Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityByShoporderRequest inValue = new Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityByShoporderRequest();
            inValue.miReleaseSfcWithActivityByShoporder = miReleaseSfcWithActivityByShoporder;
            return ((Catl.WebServices.MiReleaseSfcWithActivityServiceService.MiReleaseSfcWithActivityService)(this)).miReleaseSfcWithActivityByShoporderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityResponse1> Catl.WebServices.MiReleaseSfcWithActivityServiceService.MiReleaseSfcWithActivityService.miReleaseSfcWithActivityAsync(Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityRequest request)
        {
            return base.Channel.miReleaseSfcWithActivityAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityResponse1> miReleaseSfcWithActivityAsync(Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivity miReleaseSfcWithActivity)
        {
            Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityRequest inValue = new Catl.WebServices.MiReleaseSfcWithActivityServiceService.miReleaseSfcWithActivityRequest();
            inValue.miReleaseSfcWithActivity = miReleaseSfcWithActivity;
            return ((Catl.WebServices.MiReleaseSfcWithActivityServiceService.MiReleaseSfcWithActivityService)(this)).miReleaseSfcWithActivityAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiReleaseSfcWithActivityServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiReleaseSfcWithActivityServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://ndmesd093.catlbattery.com:50000/atlmeswebservice/MiReleaseSfcWithActivityS" +
                        "erviceService");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MiReleaseSfcWithActivityServiceClient.GetBindingForEndpoint(EndpointConfiguration.MiReleaseSfcWithActivityServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MiReleaseSfcWithActivityServiceClient.GetEndpointAddress(EndpointConfiguration.MiReleaseSfcWithActivityServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            MiReleaseSfcWithActivityServicePort,
        }
    }
}
